# Generated by Django 5.2.14 on 2026-06-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productanalytics',
            name='humidity',
        ),
        migrations.AddField(
            model_name='productanalytics',
            name='is_humid',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]