# Generated by Django 5.2.14 on 2026-06-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_productanalytics_temperature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productanalytics',
            old_name='is_humid',
            new_name='humidity',
        ),
        migrations.RemoveField(
            model_name='productanalytics',
            name='temperature',
        ),
        migrations.AddField(
            model_name='productanalytics',
            name='is_hot',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
